In [2]:
import pandas as pd 
import numpy as np

In [3]:
cols_needed = ['loan_amnt','term','int_rate','installment','grade','sub_grade',
               'purpose','issue_d','emp_length','home_ownership','annual_inc',
               'verification_status','addr_state','dti','earliest_cr_line',
               'fico_range_low','fico_range_high','open_acc','pub_rec',
               'revol_bal','revol_util','total_acc','loan_status']

In [4]:
fin = pd.read_csv("Data/accepted_2007_to_2018Q4.csv.gz", compression='gzip', usecols=cols_needed)

In [5]:
fin.shape

(2260701, 23)

In [6]:
fin.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 str
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   emp_length           str
 7   home_ownership       str
 8   annual_inc           float64
 9   verification_status  str
 10  issue_d              str
 11  loan_status          str
 12  purpose              str
 13  addr_state           str
 14  dti                  float64
 15  earliest_cr_line     str
 16  fico_range_low       float64
 17  fico_range_high      float64
 18  open_acc             float64
 19  pub_rec              float64
 20  revol_bal            float64
 21  revol_util           float64
 22  total_acc            float64
dtypes: float64(12), str(11)
memory usage: 396.7 MB

In [7]:
fin.isnull().sum()

loan_amnt                  33
term                       33
int_rate                   33
installment                33
grade                      33
sub_grade                  33
emp_length             146940
home_ownership             33
annual_inc                 37
verification_status        33
issue_d                    33
loan_status                33
purpose                    33
addr_state                 33
dti                      1744
earliest_cr_line           62
fico_range_low             33
fico_range_high            33
open_acc                   62
pub_rec                    62
revol_bal                  33
revol_util               1835
total_acc                  62
dtype: int64

In [8]:
df = fin.copy()

In [9]:
df.shape

(2260701, 23)

In [10]:
fin[fin.duplicated()]

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1651665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1939379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1939380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.drop_duplicates()

In [12]:
df.shape

(2260669, 23)

In [13]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,3600.0,36 months,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.0,Not Verified,...,PA,5.91,Aug-2003,675.0,679.0,7.0,0.0,2765.0,29.7,13.0
1,24700.0,36 months,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.0,Not Verified,...,SD,16.06,Dec-1999,715.0,719.0,22.0,0.0,21470.0,19.2,38.0
2,20000.0,60 months,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.0,Not Verified,...,IL,10.78,Aug-2000,695.0,699.0,6.0,0.0,7869.0,56.2,18.0
3,35000.0,60 months,14.85,829.90,C,C5,10+ years,MORTGAGE,110000.0,Source Verified,...,NJ,17.06,Sep-2008,785.0,789.0,13.0,0.0,7802.0,11.6,17.0
4,10400.0,60 months,22.45,289.91,F,F1,3 years,MORTGAGE,104433.0,Source Verified,...,PA,25.37,Jun-1998,695.0,699.0,12.0,0.0,21929.0,64.5,35.0

In [14]:
df.dropna(subset=['loan_amnt'],inplace= True)

In [15]:
df.isnull().sum()

loan_amnt                   0
term                        0
int_rate                    0
installment                 0
grade                       0
sub_grade                   0
emp_length             146907
home_ownership              0
annual_inc                  4
verification_status         0
issue_d                     0
loan_status                 0
purpose                     0
addr_state                  0
dti                      1711
earliest_cr_line           29
fico_range_low              0
fico_range_high             0
open_acc                   29
pub_rec                    29
revol_bal                   0
revol_util               1802
total_acc                  29
dtype: int64

In [16]:
# replacing 0 in place of nulls in numerical columns to fill the data
df['pub_rec']= df['pub_rec'].fillna(0)
df['open_acc']= df['open_acc'].fillna(0)
df['total_acc']= df['total_acc'].fillna(0)

In [17]:
# median value in null value holders
df['annual_inc'] = df['annual_inc'].fillna(df['annual_inc'].median())
df['dti'] = df['dti'].fillna(df['dti'].median())
df['revol_util'] = df['revol_util'].fillna(df['revol_util'].median())

#median fill up in emp_length series
df['emp_length']= df['emp_length'].fillna('Unknown')

In [18]:
# Drop only the null rows for these two columns
df.dropna(subset=['issue_d', 'earliest_cr_line'], inplace=True)

In [19]:
df.isnull().sum()

loan_amnt              0
term                   0
int_rate               0
installment            0
grade                  0
sub_grade              0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
issue_d                0
loan_status            0
purpose                0
addr_state             0
dti                    0
earliest_cr_line       0
fico_range_low         0
fico_range_high        0
open_acc               0
pub_rec                0
revol_bal              0
revol_util             0
total_acc              0
dtype: int64

In [20]:
df.shape

(2260639, 23)

In [21]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'purpose', 'addr_state', 'dti',
       'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc'],
      dtype='str')

In [22]:
df.sample(9)

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
1787217,12000.0,36 months,8.60,379.37,A,A4,8 years,MORTGAGE,55200.0,Source Verified,...,CA,21.64,Sep-2000,745.0,749.0,13.0,0.0,15915.0,34.9,22.0
526016,10000.0,60 months,19.03,259.58,D,D3,1 year,RENT,50000.0,Source Verified,...,NY,15.99,Dec-2004,660.0,664.0,9.0,0.0,19072.0,87.5,14.0
1922628,7000.0,36 months,13.11,236.23,B,B4,8 years,RENT,60000.0,Not Verified,...,AK,18.32,Dec-2004,690.0,694.0,5.0,0.0,22000.0,89.9,10.0
423471,15500.0,36 months,7.34,481.01,A,A4,10+ years,MORTGAGE,118000.0,Source Verified,...,VA,15.56,Nov-1985,680.0,684.0,14.0,1.0,12394.0,53.9,28.0
1581117,3300.0,36 months,7.96,103.35,A,A5,1 year,RENT,20000.0,Source Verified,...,CA,6.06,Nov-1976,680.0,684.0,6.0,0.0,2919.0,23.4,8.0
1687330,27000.0,36 months,8.24,849.08,B,B1,10+ years,MORTGAGE,150000.0,Verified,...,NC,9.26,Sep-1998,675.0,679.0,17.0,0.0,25497.0,33.3,32.0
2022038,8000.0,36 months,12.79,268.75,C,C1,Unknown,RENT,38800.0,Verified,...,IL,23.01,Nov-2000,665.0,669.0,10.0,0.0,5445.0,52.4,22.0
1671735,6000.0,36 months,11.49,197.83,B,B5,10+ years,RENT,45000.0,Verified,...,IL,23.01,Jun-2003,670.0,674.0,12.0,1.0,9701.0,42.9,19.0
2070841,25000.0,36 months,6.72,768.74,A,A3,2 years,MORTGAGE,40000.0,Source Verified,...,FL,31.74,Jan-2006,775.0,779.0,16.0,0.0,9876.0,22.6,27.0

In [23]:
df[[ 'issue_d', 'loan_status', 'purpose']].sample(10)

          issue_d         loan_status             purpose
1712074  Feb-2017  Late (31-120 days)         credit_card
1115890  Jan-2016          Fully Paid  debt_consolidation
2010374  Jul-2016             Current  debt_consolidation
1013737  Mar-2016          Fully Paid  debt_consolidation
1916523  Jul-2012          Fully Paid  debt_consolidation
2218905  Nov-2016          Fully Paid  debt_consolidation
86884    Oct-2015          Fully Paid  debt_consolidation
654460   Jun-2016         Charged Off      major_purchase
1586080  Apr-2018          Fully Paid  debt_consolidation
1343602  Feb-2014          Fully Paid               house

In [30]:
df.sample(9)

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
494695,20000.0,60 months,26.30,602.37,E,E5,10+ years,MORTGAGE,60000.0,Verified,...,NJ,10.70,Aug-2002,665.0,669.0,3.0,0.0,3781.0,75.6,6.0
383664,12000.0,36 months,9.49,384.34,B,B2,10+ years,MORTGAGE,70000.0,Not Verified,...,OH,12.17,Dec-2002,660.0,664.0,9.0,1.0,11744.0,72.5,30.0
312423,10000.0,36 months,6.68,307.31,A,A3,10+ years,RENT,55000.0,Not Verified,...,CA,9.45,Aug-2000,700.0,704.0,6.0,0.0,7379.0,33.5,18.0
1499031,6000.0,36 months,10.07,193.81,B,B2,10+ years,RENT,38500.0,Not Verified,...,IN,14.90,Apr-2012,705.0,709.0,3.0,0.0,7147.0,71.5,4.0
1394299,10000.0,36 months,6.46,306.31,A,A1,10+ years,MORTGAGE,85000.0,Not Verified,...,AZ,12.20,Nov-2007,720.0,724.0,6.0,0.0,7212.0,34.7,11.0
1978429,35000.0,60 months,9.49,734.90,B,B2,< 1 year,OWN,135000.0,Source Verified,...,CA,25.43,Aug-1996,680.0,684.0,14.0,0.0,52719.0,56.6,28.0
1068522,9000.0,36 months,5.32,271.04,A,A1,3 years,RENT,47500.0,Not Verified,...,TX,26.12,Mar-1999,705.0,709.0,10.0,0.0,3533.0,25.2,27.0
70011,8000.0,36 months,10.99,261.88,B,B4,10+ years,MORTGAGE,150000.0,Source Verified,...,FL,6.39,Jul-2005,665.0,669.0,15.0,0.0,13097.0,36.2,27.0
260503,8400.0,36 months,8.18,263.93,B,B1,10+ years,MORTGAGE,85000.0,Verified,...,DE,21.08,Jul-2003,660.0,664.0,11.0,0.0,32242.0,99.2,32.0

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 str
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   emp_length           str
 7   home_ownership       str
 8   annual_inc           float64
 9   verification_status  str
 10  issue_d              str
 11  loan_status          str
 12  purpose              str
 13  addr_state           str
 14  dti                  float64
 15  earliest_cr_line     str
 16  fico_range_low       float64
 17  fico_range_high      float64
 18  open_acc             float64
 19  pub_rec              float64
 20  revol_bal            float64
 21  revol_util           float64
 22  total_acc            float64
dtypes: float64(12), str(11)
memory usage: 413.9 MB